pool:
  name: Azure Pipelines
  demands: 
    - Agent.os -equals windows

jobs:
- job: A
  strategy:
    maxParallel: 2 # maximum number simultaneous matrix legs to run
  steps:
  - script: npm ci
  - script: npx playwright test --shard=1/2 

- job: B
  strategy:
    maxParallel: 2 # maximum number simultaneous matrix legs to run
  steps:
  - script: npm ci
  - script: npx playwright test --shard=2/2 